<?php

namespace CraftKeen\CMS\UserBundle\Repository;

use CraftKeen\CMS\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
     * Get users by role
     *
     * @param  [type]
     *
     * @return User[]
     */
    public function findUserByRole($role = null)
    {
    	$query = $this->createQueryBuilder('u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"'.$role.'"%')
            ->getQuery();

        return $query->getResult();
    }

    /**
     * Get brochure users
     *
     * @return User[]
     */
    public function findBrochureUsers() {
        $query = $this->createQueryBuilder('u')
            ->where('u.roles LIKE :role1')
            ->orWhere('u.roles LIKE :role2')
            ->setParameter('role1', '%ROLE_BROCHURE_EDITOR%')
            ->setParameter('role2', '%ROLE_BROCHURE_APPROVER%')
            ->getQuery();

        return $query->getResult();
    }
}
