<?php

namespace CraftKeen\FCRBundle\Repository;

use CraftKeen\CMS\AdminBundle\Entity\Language;
use CraftKeen\FCRBundle\Entity\ActiveProvince;

/**
 * ActiveProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiveProvinceRepository extends TranslatableEntityRepository
{

    /**
     * Find Active Provinces to Display on Leasing Map
     *
     * @param $language
     *
     * @return array
     */
    public function findProvincesMap(Language $language = null)
    {
        $provinces = $this->findBy(array('status' => 'live', 'lang' => $language), array('provinceName' => 'ASC'));
        $data = [];
        /**
         * @var int $key
         * @var ActiveProvince $province
         */
        foreach ($provinces as $key => $province) {
            $data[$key] = array(
                'province' => $province->getProvinceCode(),
                'slug' => strtolower($province->getProvinceCode()),
                'name' => $province->getProvinceName(),
                'lablong' => $province->getLabelLat(),
                'lablat' => $province->getLabelLng(),
                'totalArea' => $province->getTotalArea(),
                'population' => $province->getPopulation(),
                'households' => $province->getHouseholds(),
                'map_width' => $province->getIconWidth(),
                'map' => $province->getIcon(),
                'description' => $province->getDescription(),
            );
        }

        return $data;
    }
}
