<?php

namespace CraftKeen\FCRBundle\Repository;

use CraftKeen\FCRBundle\Entity\AnalystCoverage;

/**
 * AnalystCoverageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalystCoverageRepository extends TranslatableEntityRepository
{
    public function truncate()
    {
        $cmd = $this->getEntityManager()->getClassMetadata(AnalystCoverage::class);
        return $this->getEntityManager()
            ->getConnection()
            ->query('START TRANSACTION; SET FOREIGN_KEY_CHECKS=0; TRUNCATE '.$cmd->getTableName().'; SET FOREIGN_KEY_CHECKS=1; COMMIT;');
    }
}
