<?php

namespace CraftKeen\FCRBundle\Repository;
use CraftKeen\FCRBundle\Entity\CareersPosition;

/**
 * CareersPositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareersPositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function truncate()
    {
        $cmd = $this->getEntityManager()->getClassMetadata(CareersPosition::class);
        return $this->getEntityManager()
            ->getConnection()
            ->query('START TRANSACTION; SET FOREIGN_KEY_CHECKS=0; TRUNCATE '.$cmd->getTableName().'; SET FOREIGN_KEY_CHECKS=1; COMMIT;');
    }
}
