<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * CareerPositionSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareerPositionSubmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
