<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * CareersSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CareersSliderRepository extends TranslatableEntityRepository
{
}
