<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * InvestorConferenceCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConferenceCallRepository extends TranslatableEntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }
}
