<?php

namespace CraftKeen\FCRBundle\Repository;

use CraftKeen\FCRBundle\Entity\Debenture;

/**
 * DebentureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebentureRepository extends TranslatableEntityRepository
{
    public function truncate()
    {
        $cmd = $this->getEntityManager()->getClassMetadata(Debenture::class);
        return $this->getEntityManager()
            ->getConnection()
            ->query('START TRANSACTION; SET FOREIGN_KEY_CHECKS=0; TRUNCATE '.$cmd->getTableName().'; SET FOREIGN_KEY_CHECKS=1; COMMIT;');
    }

	public function findAll()
    {
        return $this->findBy(array(), array('maturityDate' => 'DESC'));
    }
}
