<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * FAQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FAQRepository extends TranslatableEntityRepository
{
}
