<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * FinancialReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialReportRepository extends TranslatableEntityRepository
{
	public function findAll()
    {
        return $this->findBy(array(), array('year' => 'DESC'));
    }
}
