<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * LeasingStockValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeasingStockValueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest()
    {
        date_default_timezone_set('America/Toronto');
        $d = $this->createQueryBuilder('v')
            ->orderBy('v.created', 'DESC')
            ->setMaxResults(1)
            ->getQuery()->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);
        return $d;
    }
}
