<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * OfficeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfficeRepository extends TranslatableEntityRepository
{
}
