<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PeopleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeopleRepository extends TranslatableEntityRepository
{
}
