<?php

namespace CraftKeen\FCRBundle\Repository;

use CraftKeen\FCRBundle\Entity\PressRelease;

/**
 * PressReleaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressReleaseRepository extends TranslatableEntityRepository
{
    public function truncate()
    {
        $cmd = $this->getEntityManager()->getClassMetadata(PressRelease::class);
        return $this->getEntityManager()
            ->getConnection()
            ->query('START TRANSACTION; SET FOREIGN_KEY_CHECKS=0; TRUNCATE '.$cmd->getTableName().'; SET FOREIGN_KEY_CHECKS=1; COMMIT;');
    }

    /**
     * Find Related Press releases
     *
     * @param PressRelease $pressRelease
     * @param Integer $limit
     * @return Array
     */
    public function getRelated( PressRelease $pressRelease, $limit = 5 ) {
        return $this->findBy(['lang' => $pressRelease->getLang()], ['date' => 'DESC'], $limit);
    }
}
