<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertyDetailsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyDetailsRepository extends \Doctrine\ORM\EntityRepository
{
}
