<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertyFeatureSliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyFeatureSliderRepository extends TranslatableEntityRepository
{
}
