<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertyGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
