<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertyVacancyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyVacancyRepository extends \Doctrine\ORM\EntityRepository
{
}
