<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertySubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertySubmissionRepository extends \Doctrine\ORM\EntityRepository
{
}
