<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertyDemographicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyDemographicRepository extends \Doctrine\ORM\EntityRepository
{
}
