<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * PropertyFilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyFilterRepository extends \Doctrine\ORM\EntityRepository
{
}
