<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * RetailArtCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailArtCategoryRepository extends TranslatableEntityRepository
{
}
