<?php

namespace CraftKeen\FCRBundle\Repository;
use CraftKeen\FCRBundle\Entity\RetailArt;
use CraftKeen\CMS\AdminBundle\Entity\Language;

/**
 * RetailArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailArtRepository extends TranslatableEntityRepository
{
    /**
     * @param RetailArt $parent
     * @param Language $language
     *
     * @return null|RetailArt|object
     */
    public function findTranslation(RetailArt $parent, Language $language)
    {
        return $this->findOneBy(['langParent' => $parent, 'lang' => $language]);
    }

    /**
     * @param Page $parent
     *
     * @return mixed
     */
    public function getRelated(RetailArt $parent)
    {
        $qb = $this->createQueryBuilder('p');
        $qb ->where('p.lang = :lang')
            ->setParameter('lang', $parent->getLang())
            ->andWhere('p.id != :postId')
            ->setParameter('postId', $parent->getId());

        return $qb->getQuery()
              ->getResult();
    }
}
