<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * SustainabilitySliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustainabilitySliderRepository extends TranslatableEntityRepository
{
}
