<?php

namespace CraftKeen\FCRBundle\Repository;

/**
 * SustainabilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SustainabilityRepository extends TranslatableEntityRepository
{
}
