<?php

namespace CraftKeen\CMS\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InboxRepository extends EntityRepository
{
    /**
     * @param $user
     *
     * @return array
     */
    public function findInbox($user)
    {
        return $this->findBy(['recipient' => $user], ['isRead' => 'ASC', 'created' => 'DESC']);
    }

    /**
     * @param $user
     *
     * @return int
     */
    public function findNew($user)
    {
        $messages = $this->findBy(['recipient' => $user, 'isRead' => false]);

        return count($messages);
    }
}
