<?php

namespace CraftKeen\BrochureBuilderBundle\Repository;

use CraftKeen\BrochureBuilderBundle\Entity\Brochure;
use CraftKeen\FCRBundle\Entity\Property;
use Doctrine\ORM\EntityRepository;

/**
 * BrochureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrochureRepository extends EntityRepository
{

    /**
     * Retrieve list of non-deleted brochures. Especially for user.
     *
     * @return array
     */
    public function findNotDeleted() {
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.status != :status')
            ->addOrderBy('b.id', 'DESC')
            ->setParameter('status', Brochure::STATUS_DELETED);

        return $qb->getQuery()->getResult();
    }

    /**
     * Get active brochure for property (with live status)
     *
     * @param Property $property
     * @return Brochure
     */
    public function getBrochureForProperty(Property $property) {
        $qb = $this->createQueryBuilder('b');
        $qb->where('b.status = :status')
           ->andWhere('b.property = :property')
           ->setParameter('status', Brochure::STATUS_LIVE)
           ->setParameter('property', $property);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
