<?php

namespace CraftKeen\BrochureBuilderBundle\Repository;

/**
 * BrochureDemographicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrochureDemographicRepository extends \Doctrine\ORM\EntityRepository
{
}
