<?php

namespace CraftKeen\BrochureBuilderBundle\Repository;

/**
 * BrochureImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrochureImageRepository extends \Doctrine\ORM\EntityRepository
{
}
