<?php

namespace CraftKeen\BrochureBuilderBundle\Repository;

/**
 * BrochurePlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrochurePlanRepository extends \Doctrine\ORM\EntityRepository
{
}
